### PR TITLE
Fixes compilation errors, removes lifetimes

### PR DESCRIPTION
**Pull request by DuncanConroy**
Hello Sir,
hope this helps moving forward :)
For async work, you might want to look at https://tokio.rs

### CODE REVIEW

**Comment by jpaulm** [comment]
That's fantastic!  I haven't tested it, but it looks better already!  Obviously I need to research the new functions uou have introduced, so this is a learning opportunity as well!  Thanks a million!

BTW Whom do I thank: Duncan or Daniel?!  :-)

**Comment by DuncanConroy** [comment]
Glad it helped! Daniel is my real name ;)

**Comment by jpaulm** [comment]
Sorry to bother you, but I wonder if you could do your magic again...!  

Have promoted another buggy version: the main thing I am trying to is stick a ref to some code in the `Process` block (renamed from `FBPProcess`) - basically that's it.  I can see that this code needs access to the 'conn' variable...  does this have to be a parameter?  If so,(or not), how?!  I stuck an `&conn` on the definition of `proc1`, but don't know how to pick it up!

Also the types on the Foos confuse me!  

Help would be much appreciated!  TIA

**Comment by jpaulm** [comment]
Sorry @DuncanConroy I realized that I can hang the `conn` off the Process block...  So my problems  are with the various types and generics on Foo!  Thanks!

**Comment by jpaulm** [comment]
I think I'm making progress - at least the number of errors is going down...!

**Comment by jpaulm** [comment]
Hi @DuncanConroy , I went back to your last good version, for which Danke!  I have made some changes, which I am hoping you can use to figure out my intent!  Apart from syntax problems, I am not sure how to get the `execute` closure to access the 'conn' variable.  If I move that into Process, the closure still has to access the Process... I have moved 'spawn' up into Process 'impl' - not sure if I can do that!   Thanks for any help you can give me!

**Comment by DuncanConroy** [comment]
Hi @jpaulm,
Rust makes it quite hard, passing closures around (due to the ownership handling).
I stumbled upon your FBP page a few years ago, so I'm kind of familiar with what you might be trying to do :)
I would highly recommend walking through this tutorial of tokio.rs: https://tokio.rs/tokio/tutorial
They build a redis server (https://github.com/tokio-rs/mini-redis), which can communicate messages between tasks using channels. A big advantage is that tokio uses "green threading", so we don't occupy threads while they're idling.
I think this might be what you're looking for?
It's amazing to see you still developing software ;)

Best,
Daniel

**Comment by jpaulm** [comment]
Hi Daniel, I think I would like to continue along the current lines for now...  It's great that you are familiar with FBP - that makes things a lot easier...  My gut feel is that I'm fairly close - almost all the error messages in `cargo run` have to do with the `exec` field, which I want to use to hold a (reference to a?) closure...  I haven't been able to internalize the syntax for `exec` in Process - I assume it breaks down into smaller syntactic elements...?  

I'm not even sold on closures - I am really not clear on the difference between closures and functions... except that some of the docs imply that closures can access the "external" variables...  Also, I don't think I'm passing closures around - I just want to store the closure that does the component logic into the Process, so that I can invoke it on line 88 ...    

Some of the error messages from `cargo run` are so obscure that they might as well say, "try stuff at random until it works!" :-)

`Process execute` is the scheduling part of the Process  (like `run` in https://github.com/jpaulm/javafbp/blob/master/src/main/java/com/jpaulmorrison/fbp/core/engine/Component.java - line 985) , while `mySender` is the process-specific part of the process execution (in Java it's coded in the Compoent code, so `mySender` will have to be a separate source module after I tackle linkage issues...) - you will notice that I gave it a name, so it doesn't even have to be a closure, if that would make life easier...! 

I'll worry about `JoinHandle` later!  

Any help you could give me would be great... or should I just give up?!  And yes, after working for 60 years at trying to _simplify_ programming, someone comes up with something like Rust!  At least, it isn't JavaScript!  :-)  

TIA

Paul

**Pull request merged**
